---
env:
  node: true
root: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:promise/recommended
  - google
  - prettier
rules:
  require-jsdoc: 0
  sort-imports:
    - error
    - ignoreDeclarationSort: true
  import/order:
    - error
    - alphabetize:
        order: asc
      newlines-between: always
